on: [push]
name: Test commit

jobs:
    test-it:
        name: Test PR
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - run: date >> test
            - run: git diff
            - uses: peter-evans/create-pull-request@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}                    
                  commit-message: Update test file as of ${{ github.sha }}
                  title: Update time in ${{ github.ref }}
                  branch: update-time-bot/${{ github.ref }}
                  assignees: ${{ github.actor }}

            - uses: unsplash/comment-on-pr@v1.2.0
              if: github.event_name == 'pull_request'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  msg: |
                    Check out #${{ env.PULL_REQUEST_NUMBER }}
                    
                  
                