on: [push]
name: Test commit

jobs:
    test-it:
        name: Test PR
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - uses: docker://oskarstark/php-cs-fixer-ga:2.15.3
            - uses: peter-evans/create-pull-request@v2
              id: cpr
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}                    
                  commit-message: Apply php-cs-fixer changes as of ${{ github.sha }}
                  title: Fix coding standards in ${{ github.ref }}
                  branch: php-cs-fixer/${{ github.ref }}
                  assignees: ${{ github.actor }}
                  body: |
                    Please apply these changes on the ${{ github.ref }} branch to fix coding standard violations.

            - uses: unsplash/comment-on-pr@v1.2.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              if: steps.cpr.outputs.pr_number
              with:
                  msg: |
                    @${{ github.actor }} please apply the coding standard fixes from #${{ steps.cpr.outputs.pr_number }}
                    
                  
                